# Generated by Django 4.2.2 on 2023-07-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_bodypart_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='body_part',
            new_name='part_num',
        ),
        migrations.AddField(
            model_name='bodypart',
            name='part_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
